### ISSUE TITLE
Please let everybody finish the speedrun

### ISSUE THREAD

**Issue by DrahcPro** [explosivegaming/factorio-olympics#42]
**Feature overview**
Name: Speedrun all finish
TL;DR: at the moment when the first person finishes the game finishes, please change this so everybody can set a time.

**Comment by Hornwitser** [comment]
I second this.  It's jarring to have the game suddenly end, and it would make a lot more sense score wise if everyone had a time they finished with.

**Comment by Cooldude2606** [comment]
Currently its just ends as the finish time is not recorded to airable, and if everyone was allowed to finish then everyone would end with the same score of 100%. In order to fix this we will need to rework the scoring system for speedrun. With #32 added we could provide both the progress at point of first team completion as well as they final time.

**Comment by Hornwitser** [comment]
Score could be changed to time in seconds without having to change anything else.

**Comment by Cooldude2606** [comment]
Pr has been merged, closing issue.
